#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker tag clarksnut/clarksnut-ui clarksnut/clarksnut-ui:$(git rev-parse --short HEAD);
docker tag clarksnut/clarksnut-ui-openshift clarksnut/clarksnut-ui-openshift:$(git rev-parse --short HEAD);
docker push clarksnut/clarksnut-ui
docker push clarksnut/clarksnut-ui-openshift
